name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the website image to docker hub
      run: docker build -f Dockerfile -t rickchinois/xivloot-app:latest .
    - name: Push website image to docker hub
      run: |
        docker login -u rickchinois -p ${{secrets.DOCKER_HUB_TOKEN}}
        docker push rickchinois/xivloot-app:dev
